# Generated by Django 5.1 on 2025-11-20 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vt_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mitigationaction',
            name='aws_resource_id',
        ),
        migrations.AddField(
            model_name='awsconfiguration',
            name='isolation_sg_id',
            field=models.CharField(blank=True, help_text='Quarantine SG ID', max_length=50),
        ),
        migrations.AddField(
            model_name='awsconfiguration',
            name='log_group_name',
            field=models.CharField(blank=True, help_text='CloudWatch Log Group Name', max_length=100),
        ),
        migrations.AddField(
            model_name='awsconfiguration',
            name='nacl_id',
            field=models.CharField(blank=True, help_text='Network ACL ID', max_length=50),
        ),
        migrations.AddField(
            model_name='awsconfiguration',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aws_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='awsconfiguration',
            name='waf_ip_set_id',
            field=models.CharField(blank=True, help_text='WAF IP Set ID', max_length=100),
        ),
        migrations.AddField(
            model_name='awsconfiguration',
            name='waf_ip_set_name',
            field=models.CharField(blank=True, help_text='WAF IP Set Name', max_length=100),
        ),
        migrations.AddField(
            model_name='awsconfiguration',
            name='waf_web_acl_id',
            field=models.CharField(blank=True, help_text='WAF Web ACL ID', max_length=100),
        ),
        migrations.AddField(
            model_name='awsconfiguration',
            name='waf_web_acl_name',
            field=models.CharField(blank=True, help_text='WAF Web ACL Name', max_length=100),
        ),
        migrations.AddField(
            model_name='mitigationaction',
            name='rule_number',
            field=models.IntegerField(default=100, help_text='Rule Number for NACL actions'),
        ),
        migrations.AlterField(
            model_name='awsconfiguration',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='awsconfiguration',
            name='network_firewall_arn',
            field=models.CharField(blank=True, help_text='Network Firewall Policy ARN', max_length=255),
        ),
        migrations.AlterField(
            model_name='awsconfiguration',
            name='security_group_id',
            field=models.CharField(blank=True, help_text='Default SG for Blocking', max_length=50),
        ),
        migrations.AlterField(
            model_name='awsconfiguration',
            name='vpc_id',
            field=models.CharField(blank=True, help_text='VPC ID (Required for NACL)', max_length=50),
        ),
        migrations.AlterField(
            model_name='mitigationaction',
            name='action_type',
            field=models.CharField(choices=[('block_ip', 'Block IP (Security Group)'), ('block_ip_waf', 'Block IP (WAF)'), ('block_ip_nacl', 'Block IP (NACL)'), ('isolate_instance', 'Isolate Instance (Quarantine)'), ('geo_block', 'Geo Block (WAF)'), ('rate_limit', 'Set Rate Limit (WAF)'), ('update_firewall', 'Update Network Firewall'), ('investigate', 'Further Investigation'), ('alert', 'Send Alert')], max_length=30),
        ),
        migrations.AlterField(
            model_name='mitigationaction',
            name='target_value',
            field=models.CharField(help_text='IP, Instance ID, or Country Codes', max_length=255),
        ),
    ]
