# Generated by Django 5.1 on 2025-11-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vt_analyzer', '0002_remove_mitigationaction_aws_resource_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='awsconfiguration',
            name='aws_session_token',
            field=models.CharField(blank=True, help_text='Session token for AWS Academy or temporary credentials', max_length=2000, null=True),
        ),
    ]
